CREATE WAREHOUSE MY_WH warehouse_size='Large';
CREATE OR REPLACE DATABASE FROSTY_FRIDAY;
USE SCHEMA PUBLIC
CREATE OR REPLACE STAGE FROSTY_FRIDAY.PUBLIC.FF_S3
    url = 's3://frostyfridaychallenges/challenge_1/';
LIST @FROSTY_FRIDAY.PUBLIC.FF_S3;

CREATE FILE FORMAT VARIANT_FORMAT
TYPE='CSV',FIELD_DELIMITER=none;
SELECT $1 from @FF_S3 (file_format=>'VARIANT_FORMAT');

CREATE OR REPLACE TABLE W1_CSV_FILES
(
COL1 TEXT,
LOADED TIMESTAMP_NTZ(9));

COPY INTO W1_CSV_FILES
FROM (SELECT $1,CURRENT_TIMESTAMP() FROM @FF_S3)
FILE_FORMAT='VARIANT_FORMAT';


SELECT * FROM W1_CSV_FILES;

SELECT * FROM INFORMATION_SCHEMA.LOAD_HISTORY;
